UKHomeOffice/asl-internal-api

lib/api.js
The non-internet-facing services use self-signed certificates, so we need to disable SSL verification or the proxy doesn't work.
=> Disable SSL verification

lib/api.js, lib/middleware/proxy.js, package-lock.json, package.json
Because we were applying the proxy middleware after body parsing then the request bodies were not being sent correctly on proxied requests that contains a body, and the requests would hang.
By using `http-proxy` directly then the body can be manually set, and PUT/POST requests can work correctly.
=> Fix request bodies on PUT/POST proxied requests

lib/routers/search/project.js
This was removed from the query, but not from the count so now it says:
> Showing 1068 of 990 results
=> Include non-active projects in count

lib/api.js, lib/error-handler.js
There was an error handler middleware defined, but it wasn't being used, which meant that clients got a gnarly JSON parsing error rather than the actual error.
=> Use error handler

lib/middleware/proxy.js
Handle error connecting to downstream service in proxy middleware. Currently an error connecting downstream crashes the entire service instead of just the request.
=> Add error handler to proxy middleware

lib/error-handler.js
This means it will use winston logger, which can be configured to pass JSON log formats instead of strings, which in turn makes using kibana to read logs in ACP _a lot_ nicer.
=> Use req.log for logging errors

lib/api.js, lib/error-handler.js
* Move the error handler to below the proxy, so that it can handle proxy errors.
* Default the error status before checking it in the error handelr so that errors with no statuses (most unhandled ones) are logged.
=> Ensure all errors are logged correctly

lib/middleware/proxy.js
Where API services have been made public then the host header for the proxied request needs to match that configured on the ingress as the url for the service. Otherwise the proxied request is redirected back to the source service on account of its host header, and it throws into an infinite loop.
=> Modify host header when proxying to public ui

lib/routers/search/profile.js
As well as matching the name, allow ASRU users to search by partial email address when finding profiles.
=> Allow search by email addresses

lib/api.js
Allows the UI to make requests directly to the metrics router on workflow.
=> Proxy metrics endpoints from workflow

lib/routers/search/project.js
Because `filterSubmittedDrafts` does a `joinRelation` with project versions it was counting some projects twice and so the total number of projects was returning incorrectly.
Add a distinct clause to ensure every project is included only once.
=> Refactor project search count function to not count multiple projects

lib/routers/search/establishment.js, lib/routers/search/profile.js
Sometimes they're coming back as integers and sometimes as strings. Make sure they're always integers.
=> Ensure counts are always returned to the client as integers

lib/routers/profile.js
Prevents bug where a project with several versions appears multiple times on a user's profile.
=> Ensure projects are distinct on profile endpoint

lib/routers/billing.js
All the client does in this context is redirect to the appropriate year, so don't bother loading data that isn't used.
=> Respond with only the year if requesting billing with no year

lib/routers/billing.js
These don't need to do any of the additional queries to load data so move them to the top and exit early when they're hit.
=> Move waiver routes to top of router

lib/routers/billing.js, package-lock.json, package.json
We have fee data for 2019/20 and 2020/21 both live now. Since we're just beyond the end of the financial year the most likely default year will be the just ended one. Make that default until January, when the soon-to-end year will be default for fees display.
=> Make previous years licence fees the default

config.js, lib/api.js
If the server is configured with a search service, and the request has it enabled then proxy to the search service instead of suing DB search.
=> Proxy requests to experimental search service if enabled

lib/api.js, lib/routers/tasks/deadline-passed.js, lib/routers/tasks/exemption.js, lib/routers/tasks/extend.js, lib/routers/tasks/index.js
This allows common functionality to be abstracted, and more fine-grained control over the routing.
=> Wrap all the routers mounted onto `/tasks` in a single parent router.

lib/routers/establishment.js
This can't whitelist unlicensed fields because it is also used to update licensed fields.
=> Remove field whitelist

lib/routers/rops/index.js, test/unit/api/rops.js
Formerly active establishments may still have ROPs due.
=> Remove status filter on ROPs establishment list

lib/routers/profile.js
Currently we check one of the profiles involved in a merge for open tasks, but not the other.
This prevents carrying out a profile merge if _either_ profile has any related open tasks.
=> Don't allow profile merge if either profile has open tasks

lib/routers/billing.js
The count returned should be the count _before_ pagination, and not after.
This fixes a bug where only the first 30 establishments were shown when there were more than 30, and no additional pages were available.
Also normalise case when searching on establishment name so sers don't have to input the case exactly.
=> Fix result counts in billing establishment list
