lib/api.js, lib/middleware/user.js, package-lock.json, package.json
Copies the loading/creating of user profiles from the public API and adds a check that the user is an ASRU user, throwing an error if not.
=> Add user profile middleware

lib/api.js, lib/middleware/user.js, lib/routers/profile.js
Allows a user profile to be loaded without being scoped within an establishment.
=> Add endpoint for user profile

lib/api.js, lib/routers/search/profile.js
Adds a new router for searching all profiles in the database.
=> People search

lib/api.js, lib/routers/search/establishment.js, lib/routers/search/index.js
Provide a way to search across all establishments
=> Add establishment search route

lib/routers/search/index.js, lib/routers/search/project.js
Adds a route for searching across all projects.
=> Projects search

config.js, lib/routers/profile.js, package-lock.json, package.json
This allows changes to be made to profile entities from UI.
=> Proxy PUT requests to profile endpoint through to workflow

lib/api.js, lib/routers/task-extend.js, package-lock.json, package.json
Waiting on bump to `asl-service`
=> Add task extend route

lib/routers/asru-establishment.js, lib/routers/profile.js
Also sorts the inspector / spoc option lists by last name.
=> Sort asru establishment associations alphabetically

lib/routers/profile.js, package-lock.json, package.json
Submits the data to workflow with an action of `merge`
=> Add endpoint for profile merge

lib/routers/search/establishment.js, lib/routers/search/profile.js
Enables searching establishments and profiles by PEL and PIL licence number respectively.
=> Search by licence number

lib/routers/establishment.js, package-lock.json, package.json
~Waiting on workflow PR https://github.com/UKHomeOffice/asl-workflow/pull/179~
=> Add create establishment route

lib/routers/profile.js, package-lock.json, package.json
needs https://github.com/UKHomeOffice/asl-workflow/pull/191
and
https://github.com/UKHomeOffice/asl-service/pull/175
=> Profile to be merged cannot have open tasks

lib/api.js, lib/routers/project.js
Waiting on https://github.com/UKHomeOffice/asl-workflow/pull/198
=> Allow ASRU LOs to update the issue date of a project

lib/routers/billing.js, package-lock.json, package.json
Adds endpoints to get high-level billing data and a datatable of establishments
WIP pending https://github.com/UKHomeOffice/asl-constants/pull/14
=> Add consolidated billing endpoints

lib/routers/search/establishment.js, lib/routers/search/project.js
* Added filter options to get statuses for ui
* Filter by status
=> Feature - global est and project status filter

lib/routers/profile.js
Allows accessing a list of tasks relating to a profile
=> Add endpoint for profile tasks

lib/routers/establishment.js
Waiting on https://github.com/UKHomeOffice/asl-workflow/pull/214
=> Revoke establishment licence

lib/routers/project.js
~Waiting on https://github.com/UKHomeOffice/asl-resolver/pull/137~
=> Allow deletion of project stubs

lib/routers/project.js
~Waiting on https://github.com/UKHomeOffice/asl-workflow/pull/232~
=> Allow update of project stub licence number

lib/api.js, lib/routers/reports.js, package-lock.json, package.json
This provides a list of all PIL which are due or overdue a 5 year review
=> Implement endpoint for first report - PIL reviews due

lib/routers/establishment.js
* Error from workflow was being swallowed and spun forever
=> Bugfix - throw error from est create

lib/api.js
Needs https://github.com/UKHomeOffice/asl-search/pull/12
=> Allow asl-search to handle null queries

lib/api.js, lib/routers/task-deadline-passed.js, lib/routers/task-exemption.js, lib/routers/tasks/index.js, package-lock.json, package.json
~requires https://github.com/UKHomeOffice/asl-service/pull/206
and https://github.com/UKHomeOffice/asl-service/pull/208~
=> Add route for handling ppl deadline exemptions

lib/routers/billing.js, package-lock.json, package.json
Pivot to basing billing on Profiles with PILs and not PILs directly.
WIP until https://github.com/UKHomeOffice/asl-schema/pull/378
=> Use Profile methods to fetch billable PILs

lib/api.js, lib/routers/asru-profiles.js, package-lock.json, package.json
~needs: https://github.com/UKHomeOffice/asl-schema/pull/386~
=> List and search ASRU profiles

lib/api.js, lib/routers/billing.js, package-lock.json, package.json
This query does not change often, but takes 25-30 seconds to run on prod, so being able to serve a fast cached version is preferable to waiting 30 seconds for the page to load each time.
=> Use DocumentCache model for storing consolidated fees query

lib/routers/profile.js, package-lock.json, package.json
When querying a user's global profile include the AA information on any projects they hold.
=> Include Additional Establishments in global profile

lib/middleware/whitelist.js, lib/routers/establishment.js, package-lock.json, package.json
* Bumped schema with cjsm
* Added est endpoint for updating arbitrary field
=> Feature - CJSM

lib/routers/tasks/filtered.js, lib/routers/tasks/index.js, package-lock.json, package.json
waiting on 
* ~https://github.com/UKHomeOffice/asl-workflow/pull/357~
* ~https://github.com/UKHomeOffice/asl-service/pull/215~
=> Add route for fetching filtered tasks from workflow

lib/routers/tasks/index.js
Pretty sure this doesn't actually get hit, so removing.
=> Remove redundant code

lib/routers/profile.js, package-lock.json, package.json
There is a field with the same name on a project version now, so the table needs to be specified.
=> Specify projects.licenceHolderId in profile query

lib/api.js, lib/routers/rops/index.js
Adds endpoints for creating and fetching ROPs exports.
=> Add routing to handle ROPs exports

.drone-1.0.yml, lib/api.js, lib/middleware/proxy.js, package-lock.json, package.json, test/data/ids.js, test/data/index.js, test/helpers/api.js, test/helpers/db.js, test/helpers/with-user.js, test/helpers/workflow.js, test/unit/api/rops.js
The previous PR was missing the schema update required to make it work, but because there was zero unit test coverage this didn't get caught.
Add some coverage.
=> Add unit test coverage

lib/routers/rops/index.js, package-lock.json, package.json, test/data/ids.js, test/data/index.js, test/unit/api/rops.js
~needs https://github.com/UKHomeOffice/asl-schema/pull/482~
=> Add endpoint for rops summary

lib/routers/tasks/assign.js, lib/routers/tasks/index.js, package-lock.json, package.json
* bumped service with task assign function
* added router to handle task assign
=> Feature - assign task

lib/routers/billing.js
The number of PILs in prod (~20,000) makes the billing query across all establishments quite slow, and so rendering the table currently times out occasionally.
We already keep a copy of all the data in the table in memory as part of the cache to serve the total fees data. We can use this to render the table without having to go to the database to do a sort and filter.
This means we should be able to serve the page reliably in a fraction of a second from the cached data.
=> Use cached data for establishment licence fees table

config.js, lib/api.js, lib/middleware/metrics.js, lib/routers/asru-workload.js, package-lock.json, package.json
needs: 
- https://github.com/UKHomeOffice/asl-metrics/pull/97
=> Add caching proxy route for fetching staff workload metrics

lib/routers/asru-workload.js
Also strip unassigned from the displayed results when viewing completed stats.
=> Change default sort order to name asc

lib/routers/establishment.js, lib/routers/pil.js, lib/routers/project.js, package-lock.json, package.json
Provide endpoints for suspending and reinstating licences.
=> Feature: suspend / reinstate licences

lib/routers/asru-profiles.js, package-lock.json, package.json
Needs:
- https://github.com/UKHomeOffice/asl-schema/pull/575
=> Allow fetching of former asru users

lib/routers/profile.js, package-lock.json, package.json
Needs: 
- https://github.com/UKHomeOffice/asl-schema/pull/577
=> Include profile merges on global profile data

.prettierrc, .vscode/settings.json, lib/routers/tasks/hba.js, lib/routers/tasks/index.js, package-lock.json, package.json
* Bumped service with new hba helpers
* Bumped schema with hba_token field
* added router for hba post and delete
=> feature - ASL-4299 Add assessment uploads

lib/routers/billing.js, package-lock.json, package.json
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4492
=> [ASL-4492] Hide future financial years' fees

.gitignore, package-lock.json, package.json
Keycloak Realm is now using lowercase, Keycloak URL is now using V22 instance URI, and CVE updated.
=> Keycloak V22
